// Copyright 2026 Inoland. Licensed under the Apache License, Version 2.0.

#pragma once

#include "CoreMinimal.h"
#include "Kismet/BlueprintFunctionLibrary.h"

// RuntimeAudioImporter — provides ERuntimeRAWAudioFormat so the
// generated bytes go directly into UStreamingSoundWave::AppendAudioDataFromRAW.
#include "RuntimeAudioImporterTypes.h"

#include "InoAudioFunctionLibrary.generated.h"

/**
 * Audio helper functions exposed to Blueprint, plus a small set of
 * C++-only static helpers for mono WAV / int16 PCM I/O.
 *
 * Blueprint surface (UFUNCTION):
 *   - GenerateEmptyRawAudio       — silent PCM in any ERuntimeRAWAudioFormat
 *   - GenerateDitheredSilence     — silent-sounding noise floor
 *   - SaveInt16PcmAsWav           — write a TArray<uint8> as a WAV file
 *
 * C++-only surface (static methods, INOAGENTS_API via the class
 * decoration; consumed cross-module from InoChatterboxOnnx and any
 * future TTS / audio submodule):
 *   - ReadMonoWavAsFloat32        — strict mono WAV reader (PCM16 + IEEE32)
 *   - WriteMonoInt16Wav           — float -> int16 LE -> WAV
 *   - WriteInt16PcmBytesAsWav     — int16 LE bytes -> WAV (TArrayView variant)
 *   - Int16PcmBytesToFloat32Mono  — int16 LE bytes -> float32 [-1, +1]
 *   - Float32ToInt16PcmBytesMono  — float32 -> clamped int16 LE bytes
 *
 * The C++-only helpers take TArrayView / pointer-out-error parameters
 * that aren't Blueprint-compatible, so they're plain `static` methods
 * rather than UFUNCTIONs. They were promoted here from the (now-deleted)
 * InoChatterboxAudioIO.h so a single library owns the WAV / PCM
 * primitives instead of a TTS-flavoured side header.
 */
UCLASS()
class INOAGENTS_API UInoAudioFunctionLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()

public:
    /**
     * Generate a silent raw PCM byte buffer in the chosen format.
     *
     * Output is little-endian, interleaved across channels — pass
     * directly to UStreamingSoundWave::AppendAudioDataFromRAW with
     * the matching ERuntimeRAWAudioFormat. Useful for silence gaps
     * (between sentences, padding for sync, generating test tones).
     *
     * Silence values per format:
     *   - Signed integer (Int8 / Int16 / Int32) → all-zero bytes.
     *   - Unsigned integer (UInt8 / UInt16 / UInt32) → midpoint
     *     value (0x80, 0x8000, 0x80000000) per sample, since
     *     unsigned PCM centers silence at the midpoint of its
     *     range, not zero.
     *   - Float32 → all-zero bytes (IEEE 754 0.0f).
     *
     * @param DurationMs    Length of silence in milliseconds. Clamped
     *                      to >= 0; 0 returns an empty array.
     * @param SampleRate    Sample rate in Hz (typically 16000, 22050,
     *                      24000, 44100). Clamped to [1, 192000].
     * @param NumChannels   Channel count (1 = mono, 2 = stereo).
     *                      Clamped to [1, 8].
     * @param Format        Raw sample encoding. Determines bytes-per-
     *                      sample and the silence value.
     * @return              Total bytes = (DurationMs/1000) * SampleRate
     *                                  * NumChannels * BytesPerSample,
     *                      filled with the format's silence value.
     */
    UFUNCTION(BlueprintPure, Category = "InoAgents|Audio",
              meta = (DisplayName = "Generate Empty Raw Audio"))
    static TArray<uint8> GenerateEmptyRawAudio(
        float DurationMs,
        int32 SampleRate,
        int32 NumChannels,
        ERuntimeRAWAudioFormat Format = ERuntimeRAWAudioFormat::Int16);

    /**
     * Generate silent-sounding raw PCM with a low-amplitude white-noise
     * floor ("dithered silence").
     *
     * WHY THIS EXISTS: neural-net lip-sync models (Runtime MetaHuman Lip
     * Sync, OVRLipSync, etc.) are trained on human voice recordings with
     * ambient noise. Feeding them mathematically-perfect zero-sample
     * silence is out-of-distribution input, and the model's response can
     * be anything from a static neutral pose to random mouth movement.
     * Adding an inaudible noise floor keeps the model inside its training
     * distribution so the mouth stays closed during pauses.
     *
     * The default NoiseAmplitude of 0.00015 is ~-76 dBFS — below the
     * audible threshold on any playback device, but large enough for any
     * float-input audio model to recognise "ambient room tone".
     *
     * @param DurationMs       See GenerateEmptyRawAudio.
     * @param SampleRate       See GenerateEmptyRawAudio.
     * @param NumChannels      See GenerateEmptyRawAudio.
     * @param Format           See GenerateEmptyRawAudio.
     * @param NoiseAmplitude   Peak noise deviation from silence, expressed
     *                         as a fraction of full-scale [0.0, 1.0]. For
     *                         Int16 the default maps to roughly ±5 sample
     *                         counts out of 32767. Set to 0 to get the
     *                         same output as GenerateEmptyRawAudio.
     * @return                 Byte buffer with interleaved dithered
     *                         silence, ready for AppendAudioDataFromRAW.
     */
    UFUNCTION(BlueprintPure, Category = "InoAgents|Audio",
              meta = (DisplayName = "Generate Dithered Silence"))
    static TArray<uint8> GenerateDitheredSilence(
        float DurationMs,
        int32 SampleRate,
        int32 NumChannels,
        ERuntimeRAWAudioFormat Format    = ERuntimeRAWAudioFormat::Int16,
        float NoiseAmplitude             = 0.00015f);

    /**
     * Save a 16-bit PCM mono byte buffer to disk as a playable WAV file.
     *
     * Intended as a diagnostic / debug helper: paste
     * FInoChatterboxSynthesisResult::AudioSamples straight in and get a
     * file you can open in any media player. Useful for verifying the
     * synth output when a streaming-audio pipeline somewhere else is
     * misbehaving ("is the problem my playback setup, or the bytes I
     * got from Synthesize Async?").
     *
     * Wraps the bytes with a 44-byte RIFF/fmt/data header — no
     * re-quantization, no resampling, no conversion. Byte count must
     * be a multiple of 2 (one int16 sample = 2 bytes), mono only.
     *
     * @param FilePath     Absolute or project-relative path to write
     *                     to. Parent directory must exist (use
     *                     FPaths::ProjectSavedDir() for scratch).
     * @param PcmBytes     Int16 PCM LE bytes, typically straight from
     *                     FInoChatterboxSynthesisResult::AudioSamples.
     * @param SampleRate   Typically 24000 for Chatterbox output. Stored
     *                     in the WAV header so media players know the
     *                     playback rate.
     * @return             True on successful write. False on any failure
     *                     (byte count not int16-aligned, directory
     *                     doesn't exist, permissions, disk full, etc.).
     */
    UFUNCTION(BlueprintCallable, Category = "InoAgents|Audio",
              meta = (DisplayName = "Save Int16 PCM As WAV"))
    static bool SaveInt16PcmAsWav(
        const FString& FilePath,
        const TArray<uint8>& PcmBytes,
        int32 SampleRate = 24000);

    // ---------------------------------------------------------------
    // C++-only static helpers (not BlueprintCallable — TArrayView /
    // pointer-out-error parameters aren't Blueprint-compatible).
    //
    // Promoted here from InoChatterboxAudioIO so a single library
    // owns the WAV / PCM primitives. Used cross-module from
    // InoChatterboxOnnx (and any future TTS / audio submodule) via
    // the INOAGENTS_API class decoration above.
    // ---------------------------------------------------------------

    /**
     * Read a mono WAV file from disk as float32 in [-1, +1].
     *
     * Accepted formats (strict):
     *
     *   AudioFormat=1 (PCM)        + BitsPerSample=16   → int16 scaled by 1/32768
     *   AudioFormat=3 (IEEE float) + BitsPerSample=32   → memcpy, already [-1, +1]
     *
     * Channel count MUST be 1. Sample rate is reported via
     * OutSampleRate but NOT validated — the caller decides whether a
     * mismatch vs the model's required rate is a warning or a hard
     * error. UInoChatterboxTtsSubsystem::SynthesizeAsync errors hard
     * on mismatch; smoke tests warn and feed through.
     *
     * Tolerant of extra 'LIST' / 'fact' / 'JUNK' chunks between the
     * fmt and data chunks (common for AudioFormat=3).
     *
     * Returns false on any parse / IO failure, writing a human-readable
     * message to *OutError when provided. OutSamples is cleared on
     * failure so partial reads never leak upward.
     */
    static bool ReadMonoWavAsFloat32(
        const FString& Path,
        TArray<float>& OutSamples,
        int32& OutSampleRate,
        FString* OutError = nullptr);

    /**
     * Write a mono PCM int16 WAV file at the given sample rate from
     * float32 input.
     *
     * Samples outside [-1, +1] are clamped before quantization. Returns
     * false on write failure. Self-contained WAV writer — doesn't
     * require the UE audio module to be initialized.
     *
     * Internally converts to int16 bytes via Float32ToInt16PcmBytesMono
     * and delegates the WAV-header framing to WriteInt16PcmBytesAsWav
     * below, so both the float and byte entry points produce identical
     * output.
     */
    static bool WriteMonoInt16Wav(
        const FString& Path,
        TArrayView<const float> Samples,
        int32 SampleRate);

    /**
     * Write a mono PCM int16 WAV file from already-int16-PCM bytes
     * (TArrayView variant — used by both the Blueprint-friendly
     * SaveInt16PcmAsWav above and direct C++ callers).
     *
     * Input is little-endian int16 samples packed as bytes (same shape
     * as FInoChatterboxSynthesisResult::AudioSamples). Byte count MUST
     * be a multiple of 2; returns false otherwise. Self-contained
     * writer (no UE audio module dependency).
     *
     * Runs a pure memcpy into the WAV body after writing the 44-byte
     * RIFF/fmt/data header — no per-sample work, O(N) bytes total.
     */
    static bool WriteInt16PcmBytesAsWav(
        const FString& Path,
        TArrayView<const uint8> PcmBytes,
        int32 SampleRate);

    /**
     * Convert int16 PCM little-endian bytes (typically 24 kHz mono, as
     * passed in FInoChatterboxVoice::ReferenceSamples) into float32
     * samples in [-1, +1] for the ONNX pipeline.
     *
     * Byte count must be a multiple of 2 (int16-aligned). Returns false
     * on alignment failure, with *OutError populated if non-null;
     * OutSamples is cleared on failure. x86_64 and ARM64 are both
     * little-endian, so we can reinterpret directly without a swap.
     *
     * O(NumSamples) linear scan; ~20 µs for a 5-second reference clip.
     */
    static bool Int16PcmBytesToFloat32Mono(
        TArrayView<const uint8> PcmBytes,
        TArray<float>& OutSamples,
        FString* OutError = nullptr);

    /**
     * Convert float32 samples in [-1, +1] (or anywhere; clamped
     * internally) into int16 PCM little-endian bytes, mono.
     *
     * Output byte count is exactly 2 × Samples.Num(). Same quantization
     * policy as WriteMonoInt16Wav: Clamp(v, -1, +1) * 32767, rounded
     * to nearest. No header, no padding.
     */
    static void Float32ToInt16PcmBytesMono(
        TArrayView<const float> Samples,
        TArray<uint8>& OutBytes);
};
