// Copyright 2026 Inoland. Licensed under the Apache License, Version 2.0.

#pragma once

#include "CoreMinimal.h"
#include "Kismet/BlueprintFunctionLibrary.h"

// RuntimeAudioImporter — provides ERuntimeRAWAudioFormat so the
// generated bytes go directly into UStreamingSoundWave::AppendAudioDataFromRAW.
#include "RuntimeAudioImporterTypes.h"

#include "InoAudioFunctionLibrary.generated.h"

/**
 * Audio helper functions exposed to Blueprint.
 *
 * Currently scoped to small utilities that pair well with the
 * RuntimeAudioImporter UStreamingSoundWave's AppendAudioDataFromRAW
 * path (Int16 PCM bytes).
 */
UCLASS()
class INOAGENTS_API UInoAudioFunctionLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()

public:
    /**
     * Generate a silent raw PCM byte buffer in the chosen format.
     *
     * Output is little-endian, interleaved across channels — pass
     * directly to UStreamingSoundWave::AppendAudioDataFromRAW with
     * the matching ERuntimeRAWAudioFormat. Useful for silence gaps
     * (between sentences, padding for sync, generating test tones).
     *
     * Silence values per format:
     *   - Signed integer (Int8 / Int16 / Int32) → all-zero bytes.
     *   - Unsigned integer (UInt8 / UInt16 / UInt32) → midpoint
     *     value (0x80, 0x8000, 0x80000000) per sample, since
     *     unsigned PCM centers silence at the midpoint of its
     *     range, not zero.
     *   - Float32 → all-zero bytes (IEEE 754 0.0f).
     *
     * @param DurationMs    Length of silence in milliseconds. Clamped
     *                      to >= 0; 0 returns an empty array.
     * @param SampleRate    Sample rate in Hz (typically 16000, 22050,
     *                      24000, 44100). Clamped to [1, 192000].
     * @param NumChannels   Channel count (1 = mono, 2 = stereo).
     *                      Clamped to [1, 8].
     * @param Format        Raw sample encoding. Determines bytes-per-
     *                      sample and the silence value.
     * @return              Total bytes = (DurationMs/1000) * SampleRate
     *                                  * NumChannels * BytesPerSample,
     *                      filled with the format's silence value.
     */
    UFUNCTION(BlueprintPure, Category = "InoAgents|Audio",
              meta = (DisplayName = "Generate Empty Raw Audio"))
    static TArray<uint8> GenerateEmptyRawAudio(
        float DurationMs,
        int32 SampleRate,
        int32 NumChannels,
        ERuntimeRAWAudioFormat Format = ERuntimeRAWAudioFormat::Int16);

    /**
     * Generate silent-sounding raw PCM with a low-amplitude white-noise
     * floor ("dithered silence").
     *
     * WHY THIS EXISTS: neural-net lip-sync models (Runtime MetaHuman Lip
     * Sync, OVRLipSync, etc.) are trained on human voice recordings with
     * ambient noise. Feeding them mathematically-perfect zero-sample
     * silence is out-of-distribution input, and the model's response can
     * be anything from a static neutral pose to random mouth movement.
     * Adding an inaudible noise floor keeps the model inside its training
     * distribution so the mouth stays closed during pauses.
     *
     * The default NoiseAmplitude of 0.00015 is ~-76 dBFS — below the
     * audible threshold on any playback device, but large enough for any
     * float-input audio model to recognise "ambient room tone".
     *
     * @param DurationMs       See GenerateEmptyRawAudio.
     * @param SampleRate       See GenerateEmptyRawAudio.
     * @param NumChannels      See GenerateEmptyRawAudio.
     * @param Format           See GenerateEmptyRawAudio.
     * @param NoiseAmplitude   Peak noise deviation from silence, expressed
     *                         as a fraction of full-scale [0.0, 1.0]. For
     *                         Int16 the default maps to roughly ±5 sample
     *                         counts out of 32767. Set to 0 to get the
     *                         same output as GenerateEmptyRawAudio.
     * @return                 Byte buffer with interleaved dithered
     *                         silence, ready for AppendAudioDataFromRAW.
     */
    UFUNCTION(BlueprintPure, Category = "InoAgents|Audio",
              meta = (DisplayName = "Generate Dithered Silence",
                      ToolTip   = "Silent-sounding audio with an inaudible "
                                  "noise floor so ML lip-sync models don't "
                                  "misfire on pure-zero input."))
    static TArray<uint8> GenerateDitheredSilence(
        float DurationMs,
        int32 SampleRate,
        int32 NumChannels,
        ERuntimeRAWAudioFormat Format    = ERuntimeRAWAudioFormat::Int16,
        float NoiseAmplitude             = 0.00015f);
};
